### PR TITLE
Bug: infinite timeout when reading stdout with callback

### PR DESCRIPTION
**Pull request by marcgibbons**
When `fp.register` stubs an asyncio subprocess, and a callback is provided, `process.stdout.read()` or `process.stdout.readline()` will loop infinitely. When no callback is provided, the function works as expected. 

This PR reproduces the bug with a failing test.

### CODE REVIEW

**Comment by aklajnert** [comment]
Thank you for reporting the problem and providing test for it, that's very useful. Perhaps you could mark it with `xfail` (with `strict=True`) with a ticket number, so this PR can be merged already? I don't know when I'll find a time to fix this bug.

**Comment by aklajnert** [comment]
This PR is still a draft - are you going to add something here? I was thinking that it could be merged, and an issue could be created to track this bug. I can create the issue if you want.

**Comment by marcgibbons** [comment]
@aklajnert Sure, I'll mark it as ready for review.

**Comment by aklajnert** [comment]
Thanks @marcgibbons, I've created an issue and referenced it in the test. I don't know when I'll have time to work on this as I have quite a lot on my plate right now.

**Pull request merged**
